function struct = m_cell2Struct(files)
    fields = [
    'D_x' 'D_y'
    %'Pbx'
    %'Pby'
    %'Pfitx'
    %'Pfity'
    %'T'
    %'Traps'
    %'bead_radius'
    %'eta_x'
    %'eta_y'
    %'f_3dB_filter'
    %'f_lim_low'
    %'f_lim_up'
    %'fx'
    %'fy'
    %'gamma_x'
    %'gamma_y'
    %'kappa_x'
    %'kappa_y'
    %'l'
    %'nb'
    %'rate'
    %'remove_peaks'
    %'slopes'
    %'timestamp'
    %'want_filter'
   % 'filename'
   % 'makedAsDefective'
   % 'defectiveReason'
   % 'markAsDefectiveTimeStamp'
    ];
    struct = cell2struct(files, fields, 1.0);
end
